name: Required Reviewer Environment with workflow branch-wise testing
on: 
  push:
    branches:
      - workflow_test_branchwise/main
  workflow_dispatch:
jobs:
  review-en-job:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Printing the review message  
        run: |
          echo "Start reviewing the code on GitHub"
          echo "Waiting for the approval"
          echo "......................."
          echo "Start reviewing the code on GitHub"
          echo "Waiting for the approval"
          echo "......................."
          echo "Testing the workflow with branch-wise wf and testing"
          echo "Waiting for the approval"
          echo "......................."
          echo "Branch-wise workflow testing is completed"
          echo "Waiting for the approval"
          echo "......................."
          echo "Branch-wise workflow testing is completed-Done"
          
          
